require('auto-pairs')
require('auto-tag')
require('code-comments')
require('code-complete')
require('code-hints')
require('colorizer')
require('files-search')
require('plugins')
require('settings')
require('settings/shortcuts')
require('sidebar')
require('sidebar/shortcuts')
require('status-bar')
require('syntax-hightlight')
require('tabs')
require('tabs/shortcuts')
require('theme')

