-- General
vim.o.encoding="UTF-8"
vim.o.number=true        	        	-- Show line numbers
vim.o.showbreak="++"		        	-- Wrap-broken line prefix
vim.o.textwidth=100     	          	-- Line wrap (number of cols)
vim.o.showmatch=true   	        		-- Highlight matching brace
vim.o.visualbell=true	                	-- Use visual bell (no beeping)
 
vim.o.hlsearch=true	                	-- Highlight all search results
vim.o.smartcase=true	                	-- Enable smart-case search
vim.o.ignorecase=true	              		-- Always case-insensitive
vim.o.incsearch=true	                	-- Searches for strings incrementally
 
vim.o.autoindent=true	                	-- Auto-indent new lines
vim.o.expandtab=true	                	-- Use spaces instead of tabs
vim.o.shiftwidth=2        			-- Number of auto-indent spaces
vim.o.smartindent=true	                	-- Enable smart-indent
vim.o.smarttab=true	                	-- Enable smart-tabs
vim.o.softtabstop=2       			-- Number of spaces per Tab
vim.o.backup=false                              -- Keep a copy of file
vim.o.history=10                                -- Keep 10 commands and 10 search in the history
vim.o.showcmd=false                             -- Hide current command
vim.o.wrap=false                                -- Wrap lines

vim.o.hidden=true
vim.o.updatetime=300
 
-- Advanced
vim.o.ruler=true       	        		-- Show row and column ruler information
vim.o.undolevels=1000     			-- Number of undo levels
vim.o.backspace="indent,eol,start"		-- Backspace behaviour
-- Generated by VimConfig.com

vim.cmd[[
  set nobackup
  set nowritebackup
]]
